// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bensooraj/griffon/mocks (interfaces: OSService)
//
// Generated by this command:
//
//	mockgen -destination=OSService.go -package=mocks github.com/bensooraj/griffon/mocks OSService
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	govultr "github.com/vultr/govultr/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockOSService is a mock of OSService interface.
type MockOSService struct {
	ctrl     *gomock.Controller
	recorder *MockOSServiceMockRecorder
}

// MockOSServiceMockRecorder is the mock recorder for MockOSService.
type MockOSServiceMockRecorder struct {
	mock *MockOSService
}

// NewMockOSService creates a new mock instance.
func NewMockOSService(ctrl *gomock.Controller) *MockOSService {
	mock := &MockOSService{ctrl: ctrl}
	mock.recorder = &MockOSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOSService) EXPECT() *MockOSServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockOSService) List(arg0 context.Context, arg1 *govultr.ListOptions) ([]govultr.OS, *govultr.Meta, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]govultr.OS)
	ret1, _ := ret[1].(*govultr.Meta)
	ret2, _ := ret[2].(*http.Response)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// List indicates an expected call of List.
func (mr *MockOSServiceMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOSService)(nil).List), arg0, arg1)
}
